name: Deploy to demo branch

on:
  push:
    branches:
      - main

jobs:
  deploy-demo:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1

    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
            ${{ runner.os }}-nuget-

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.103'

    - name: Publish Blogifier
      run: dotnet publish -c Release -o release --nologo

    - name: Add .nojekyll file
      run: touch release/.nojekyll

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        BRANCH: demo
        FOLDER: release